// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Week6RestaurantFinder.Data;

namespace Week6RestaurantFinder.Migrations
{
    [DbContext(typeof(RestaurantDbContext))]
    [Migration("20190212232422_newSeededData")]
    partial class newSeededData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Week6RestaurantFinder.Models.Restaurant", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<int>("StarRating");

                    b.Property<string>("URL");

                    b.HasKey("ID");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Chace's Pancake Coral",
                            StarRating = 4,
                            URL = "chace.jpg"
                        },
                        new
                        {
                            ID = 2,
                            Name = "SmallCakes",
                            StarRating = 5,
                            URL = "cupcake.png"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
