// <auto-generated />
using CMSBlogPost.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CMSBlogPost.Migrations.BlogDb
{
    [DbContext(typeof(BlogDbContext))]
    [Migration("20190510180513_addedImage")]
    partial class addedImage
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CMSBlogPost.Models.Post", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Title");

                    b.Property<string>("URL");

                    b.HasKey("ID");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "They are the best!",
                            Title = "Tacos are Delicious"
                        },
                        new
                        {
                            ID = 2,
                            Description = "Josie is the queen of the household",
                            Title = "Josie Cat"
                        },
                        new
                        {
                            ID = 3,
                            Description = "Belle loves to lay around the house and meow",
                            Title = "Belle Kitty"
                        },
                        new
                        {
                            ID = 4,
                            Description = ".NET is the bestest of the best!! We all love to code in C#!!!!!",
                            Title = ".NET ROCKS"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
